interface Profile {
    income: number;
}
interface TaxSummary {
    percentage: number | undefined;
}
interface TaxStrategy {
    (profile: Profile): TaxSummary;
}

interface TaxStrategies {
    [name: string]: TaxStrategy;
}

function defaultTaxStrategy() {
    return { percentage: undefined };
}
 
export const countries: TaxStrategies = {
    'Fiji': defaultTaxStrategy,
    'Tanzania': defaultTaxStrategy,
    'W. Sahara': defaultTaxStrategy,
    'Canada': defaultTaxStrategy,
    'United States of America': defaultTaxStrategy,
    'Kazakhstan': defaultTaxStrategy,
    'Uzbekistan': defaultTaxStrategy,
    'Papua New Guinea': defaultTaxStrategy,
    'Indonesia': defaultTaxStrategy,
    'Argentina': defaultTaxStrategy,
    'Chile': defaultTaxStrategy,
    'Dem. Rep. Congo': defaultTaxStrategy,
    'Somalia': defaultTaxStrategy,
    'Kenya': defaultTaxStrategy,
    'Sudan': defaultTaxStrategy,
    'Chad': defaultTaxStrategy,
    'Haiti': defaultTaxStrategy,
    'Dominican Rep.': defaultTaxStrategy,
    'Russia': defaultTaxStrategy,
    'Bahamas': defaultTaxStrategy,
    'Falkland Is.': defaultTaxStrategy,
    'Norway': defaultTaxStrategy,
    'Greenland': defaultTaxStrategy,
    'Fr. S. Antarctic Lands': defaultTaxStrategy,
    'Timor-Leste': defaultTaxStrategy,
    'South Africa': defaultTaxStrategy,
    'Lesotho': defaultTaxStrategy,
    'Mexico': defaultTaxStrategy,
    'Uruguay': defaultTaxStrategy,
    'Brazil': defaultTaxStrategy,
    'Bolivia': defaultTaxStrategy,
    'Peru': defaultTaxStrategy,
    'Colombia': defaultTaxStrategy,
    'Panama': defaultTaxStrategy,
    'Costa Rica': defaultTaxStrategy,
    'Nicaragua': defaultTaxStrategy,
    'Honduras': defaultTaxStrategy,
    'El Salvador': defaultTaxStrategy,
    'Guatemala': defaultTaxStrategy,
    'Belize': defaultTaxStrategy,
    'Venezuela': defaultTaxStrategy,
    'Guyana': defaultTaxStrategy,
    'Suriname': defaultTaxStrategy,
    'France': defaultTaxStrategy,
    'Ecuador': defaultTaxStrategy,
    'Puerto Rico': defaultTaxStrategy,
    'Jamaica': defaultTaxStrategy,
    'Cuba': defaultTaxStrategy,
    'Zimbabwe': defaultTaxStrategy,
    'Botswana': defaultTaxStrategy,
    'Namibia': defaultTaxStrategy,
    'Senegal': defaultTaxStrategy,
    'Mali': defaultTaxStrategy,
    'Mauritania': defaultTaxStrategy,
    'Benin': defaultTaxStrategy,
    'Niger': defaultTaxStrategy,
    'Nigeria': defaultTaxStrategy,
    'Cameroon': defaultTaxStrategy,
    'Togo': defaultTaxStrategy,
    'Ghana': defaultTaxStrategy,
    'Côte d\'Ivoire': defaultTaxStrategy,
    'Guinea': defaultTaxStrategy,
    'Guinea-Bissau': defaultTaxStrategy,
    'Liberia': defaultTaxStrategy,
    'Sierra Leone': defaultTaxStrategy,
    'Burkina Faso': defaultTaxStrategy,
    'Central African Rep.': defaultTaxStrategy,
    'Congo': defaultTaxStrategy,
    'Gabon': defaultTaxStrategy,
    'Eq. Guinea': defaultTaxStrategy,
    'Zambia': defaultTaxStrategy,
    'Malawi': defaultTaxStrategy,
    'Mozambique': defaultTaxStrategy,
    'eSwatini': defaultTaxStrategy,
    'Angola': defaultTaxStrategy,
    'Burundi': defaultTaxStrategy,
    'Israel': defaultTaxStrategy,
    'Lebanon': defaultTaxStrategy,
    'Madagascar': defaultTaxStrategy,
    'Palestine': defaultTaxStrategy,
    'Gambia': defaultTaxStrategy,
    'Tunisia': defaultTaxStrategy,
    'Algeria': defaultTaxStrategy,
    'Jordan': defaultTaxStrategy,
    'United Arab Emirates': defaultTaxStrategy,
    'Qatar': defaultTaxStrategy,
    'Kuwait': defaultTaxStrategy,
    'Iraq': defaultTaxStrategy,
    'Oman': defaultTaxStrategy,
    'Vanuatu': defaultTaxStrategy,
    'Cambodia': defaultTaxStrategy,
    'Thailand': defaultTaxStrategy,
    'Laos': defaultTaxStrategy,
    'Myanmar': defaultTaxStrategy,
    'Vietnam': defaultTaxStrategy,
    'North Korea': defaultTaxStrategy,
    'South Korea': defaultTaxStrategy,
    'Mongolia': defaultTaxStrategy,
    'India': defaultTaxStrategy,
    'Bangladesh': defaultTaxStrategy,
    'Bhutan': defaultTaxStrategy,
    'Nepal': defaultTaxStrategy,
    'Pakistan': defaultTaxStrategy,
    'Afghanistan': defaultTaxStrategy,
    'Tajikistan': defaultTaxStrategy,
    'Kyrgyzstan': defaultTaxStrategy,
    'Turkmenistan': defaultTaxStrategy,
    'Iran': defaultTaxStrategy,
    'Syria': defaultTaxStrategy,
    'Armenia': defaultTaxStrategy,
    'Sweden': defaultTaxStrategy,
    'Belarus': defaultTaxStrategy,
    'Ukraine': defaultTaxStrategy,
    'Poland': defaultTaxStrategy,
    'Austria': defaultTaxStrategy,
    'Hungary': defaultTaxStrategy,
    'Moldova': defaultTaxStrategy,
    'Romania': defaultTaxStrategy,
    'Lithuania': defaultTaxStrategy,
    'Latvia': defaultTaxStrategy,
    'Estonia': defaultTaxStrategy,
    'Germany': defaultTaxStrategy,
    'Bulgaria': defaultTaxStrategy,
    'Greece': defaultTaxStrategy,
    'Turkey': defaultTaxStrategy,
    'Albania': defaultTaxStrategy,
    'Croatia': defaultTaxStrategy,
    'Switzerland': defaultTaxStrategy,
    'Luxembourg': defaultTaxStrategy,
    'Belgium': defaultTaxStrategy,
    'Netherlands': defaultTaxStrategy,
    'Portugal': defaultTaxStrategy,
    'Spain': (profile) => {
        let tax = 0;
        if (profile.income < 12450) {
            tax = profile.income * 0.19;
        }
        if (profile.income < 20200) {
            tax = 2365.5 + (profile.income - 12450) * 0.24;
        }
        if (profile.income < 35200) {
            tax = 4729 + (profile.income - 20200) * 0.3;
        }
        if (profile.income < 60000) {
            tax = 8959 + (profile.income - 35200) * 0.37;
        } 
        if (profile.income < 300000) {
            tax = 17159 + (profile.income - 60000) * 0.45;
        }
        if (profile.income > 300000) {
            tax = 109159 + (profile.income - 300000) * 0.47;
        }
        return { percentage: tax / profile.income };
    },
    'Ireland': defaultTaxStrategy,
    'New Caledonia': defaultTaxStrategy,
    'Solomon Is.': defaultTaxStrategy,
    'New Zealand': defaultTaxStrategy,
    'Australia': defaultTaxStrategy,
    'Sri Lanka': defaultTaxStrategy,
    'China': defaultTaxStrategy,
    'Taiwan': defaultTaxStrategy,
    'Italy': defaultTaxStrategy,
    'Denmark': defaultTaxStrategy,
    'United Kingdom': defaultTaxStrategy,
    'Iceland': defaultTaxStrategy,
    'Azerbaijan': defaultTaxStrategy,
    'Georgia': defaultTaxStrategy,
    'Philippines': defaultTaxStrategy,
    'Malaysia': defaultTaxStrategy,
    'Brunei': defaultTaxStrategy,
    'Slovenia': defaultTaxStrategy,
    'Finland': defaultTaxStrategy,
    'Slovakia': defaultTaxStrategy,
    'Czechia': defaultTaxStrategy,
    'Eritrea': defaultTaxStrategy,
    'Japan': defaultTaxStrategy,
    'Paraguay': defaultTaxStrategy,
    'Yemen': defaultTaxStrategy,
    'Saudi Arabia': defaultTaxStrategy,
    'Antarctica': defaultTaxStrategy,
    'N. Cyprus': defaultTaxStrategy,
    'Cyprus': defaultTaxStrategy,
    'Morocco': defaultTaxStrategy,
    'Egypt': defaultTaxStrategy,
    'Libya': defaultTaxStrategy,
    'Ethiopia': defaultTaxStrategy,
    'Djibouti': defaultTaxStrategy,
    'Somaliland': defaultTaxStrategy,
    'Uganda': defaultTaxStrategy,
    'Rwanda': defaultTaxStrategy,
    'Bosnia and Herz.': defaultTaxStrategy,
    'Macedonia': defaultTaxStrategy,
    'Serbia': defaultTaxStrategy,
    'Montenegro': defaultTaxStrategy,
    'Kosovo': defaultTaxStrategy,
    'Trinidad and Tobago': defaultTaxStrategy,
    'S. Sudan': defaultTaxStrategy,
}
